AWSTemplateFormatVersion: '2010-09-09'
Resources:
  MyCriticalResource:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: critical-resource-bucket
    StackPolicy:
      Statement:
        - Effect: Deny
          Action: Update:Delete
          Resource: "*"
          Principal: "*"